name: Notify twitter

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: nearform-actions/github-action-notify-twitter@master
        with:
          message: |
            ${{ github.event.repository.name }} ${{ github.event.release.tag_name }} has been released! ðŸš€. Check out the release notes here ðŸ“œ: ${{ github.event.release.html_url }}
          twitter-app-key: ${{ secrets.X_API_KEY }}
          twitter-app-secret: ${{ secrets.X_API_SECRET }}
          twitter-access-token: ${{ secrets.X_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          
